name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  node_version: "18.17.1"
  pnpm_version: "9.1.2"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.pnpm_version }}
          run_install: false
          standalone: true
          dest: ~/setup-pnpm

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node_version }}
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: code formatting
        run: |
          pnpm prettier

      - name: Runs lint
        run: |
          pnpm lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          path: . # The root location of your Astro project inside the repository. (optional)
          node-version: ${{ env.node_version }}
          package-manager: pnpm@${{ env.pnpm_version }}
